# Generated by Django 5.0.6 on 2024-07-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='imageUrl',
            new_name='image',
        ),
    ]
